import type { Metadata } from "next";
import StyledComponentsRegistry from "./lib/registry";
import { GlobalStyles } from "@/theme/globals";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <body>{children}</body>
        <GlobalStyles />
      </StyledComponentsRegistry>
    </html>
  )
}
